### ISSUE TITLE
Allow enums as type for code decorated with SelectOneAttribute?

### ISSUE THREAD

**Issue by tomahg** [Stekeblad/stekeblad.optimizely.analyzers#1]
Suggestion:
Currently code decorated with SelectOneAttribute should be of type string or int.
Would you consider adding enum to the list of allowed types?

Current:
https://github.com/Stekeblad/stekeblad.optimizely.analyzers/blob/master/doc/Analyzers/SOA1014.md

**Comment by Stekeblad** [comment]
Enum selection factories did not cross my mind, I will look into allowing enums in the analyzer

**Comment by Stekeblad** [comment]
Hi @tomahg 

I have added enums as allowed types when using selection factory attributes. I don't think I will be able to publish an update this week but hope to get it done during the next.

**Comment by tomahg** [comment]
Excellent! Looking forward to building with zero warnings! 😁

**Comment by Stekeblad** [comment]
Version 1.3.1 is now available on the Visual Studio marketplace and on the Optimizely nuget feed.

**Comment by tomahg** [comment]
Thank you! Updated, tested and approved! 🤩
